import { execFile } from 'child_process';
import * as vscode from 'vscode';
import { serial } from '../util/serial';
import { moduleOf } from './analysisPlan';
import { extractFacts, FileFacts, languageOf, resolveImport } from './facts';

/**
 * One file in `brain/map.json`. `note` is the user's own line and is never overwritten; `summary` is the
 * pair's one-line reading of the file from "Analyse this project", kept until the next analysis.
 */
export interface MapEntry extends Omit<FileFacts, 'imports'> {
	readonly imports: string[];
	importedBy: string[];
	readonly note?: string;
	readonly summary?: string;
	/** Hash of the text the summary was written from; a different hash means the summary is out of date. */
	readonly summaryHash?: string;
	/** For long files: what each piece does, so the pair knows where to look without reading it all. */
	readonly pieces?: PieceSummary[];
}

export interface PieceSummary {
	readonly start: number;
	readonly end: number;
	readonly summary: string;
}

/** What "Analyse this project" learned about one file. */
export interface FileSummary {
	readonly summary: string;
	readonly hash: string;
	readonly pieces?: PieceSummary[];
}

/**
 * The best one-line description of a file: the user's note, then the pair's summary of the whole file, then the
 * leading doc comment (which often describes only the first declaration).
 */
export function describeEntry(entry: MapEntry | undefined): string {
	return entry?.note ?? entry?.summary ?? entry?.role ?? (entry?.exports.length ? `exports ${entry.exports.slice(0, 4).join(', ')}` : '');
}

export interface BrainMap {
	readonly builtAt: string;
	readonly commit: string;
	readonly files: Record<string, MapEntry>;
	/** A few sentences per part of the project (keyed like `src/api`), from "Analyse this project". */
	readonly modules?: Record<string, string>;
	/** Code files left out because they are too large to read. */
	readonly tooLarge?: string[];
	/** True when the project has more code files than the brain reads. */
	readonly fileLimitHit?: boolean;
}

export const SOURCE_GLOB = '**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs,py,rs,go,c,h,cc,cpp,cxx,hh,hpp,hxx}';
export const EXCLUDE_GLOB = '{**/node_modules/**,**/.git/**,**/dist/**,**/out/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/target/**,**/vendor/**,**/.my_editor/**,**/*.d.ts,**/*.min.js}';
export const MAX_FILES = 5_000;
const MAX_FILE_BYTES = 400_000;
const AUTO_START = '<!-- my_editor:auto — regenerated by "Build Project Brain"; edit outside these markers -->';
const AUTO_END = '<!-- /my_editor:auto -->';
const INDEX_BUDGET_CHARS = 7_000;

function root(): vscode.Uri | undefined {
	return vscode.workspace.workspaceFolders?.[0]?.uri;
}

function brainUri(name: string): vscode.Uri | undefined {
	const r = root();
	return r && vscode.Uri.joinPath(r, '.my_editor', 'brain', name);
}

export async function readText(uri: vscode.Uri): Promise<string | undefined> {
	try {
		return new TextDecoder().decode(await vscode.workspace.fs.readFile(uri));
	} catch {
		return undefined;
	}
}

function gitHead(cwd: string): Promise<string> {
	return new Promise(resolve => execFile('git', ['rev-parse', '--short', 'HEAD'], { cwd, timeout: 4000 }, (err, out) => resolve(err ? '' : out.trim())));
}

export async function readMap(): Promise<BrainMap | undefined> {
	const uri = brainUri('map.json');
	const text = uri && await readText(uri);
	try {
		return text ? JSON.parse(text) as BrainMap : undefined;
	} catch {
		return undefined;
	}
}

/** Recomputes `importedBy` for every entry from the resolved imports. */
function link(files: Record<string, MapEntry>): void {
	for (const entry of Object.values(files)) {
		entry.importedBy = [];
	}
	for (const [path, entry] of Object.entries(files)) {
		for (const target of entry.imports) {
			files[target]?.importedBy.push(path);
		}
	}
}

function toEntry(path: string, text: string, known: ReadonlySet<string>, previous: MapEntry | undefined): MapEntry {
	const facts = extractFacts(path, text);
	const imports = facts.imports
		.map(spec => resolveImport(path, spec, known))
		.filter((p): p is string => !!p);
	return {
		...facts, imports, importedBy: [],
		...(previous?.note ? { note: previous.note } : {}),
		...(previous?.summary ? { summary: previous.summary, summaryHash: previous.summaryHash } : {}),
		...(previous?.pieces ? { pieces: previous.pieces } : {}),
	};
}

/** Scans the whole workspace and writes `brain/map.json` and the auto section of `brain/index.md`. */
export async function buildBrain(progress?: vscode.Progress<{ message?: string }>): Promise<BrainMap | undefined> {
	const r = root();
	if (!r) {
		return undefined;
	}
	const sources = (await vscode.workspace.findFiles(SOURCE_GLOB, EXCLUDE_GLOB, MAX_FILES))
		.map(uri => ({ uri, path: vscode.workspace.asRelativePath(uri, false) }))
		.sort((a, b) => a.path.localeCompare(b.path));
	const known = new Set(sources.map(s => s.path));
	const before = await readMap();
	const previous = before?.files ?? {};
	const files: Record<string, MapEntry> = {};
	const tooLarge: string[] = [];
	for (const [i, { uri, path }] of sources.entries()) {
		if (i % 200 === 0) {
			progress?.report({ message: `${i} of ${sources.length} files` });
		}
		const stat = await vscode.workspace.fs.stat(uri);
		if (stat.size > MAX_FILE_BYTES) {
			tooLarge.push(path);
			continue;
		}
		const text = await readText(uri);
		if (text !== undefined) {
			files[path] = toEntry(path, text, known, previous[path]);
		}
	}
	link(files);
	const map: BrainMap = {
		builtAt: new Date().toISOString(), commit: await gitHead(r.fsPath), files,
		...(before?.modules ? { modules: before.modules } : {}),
		...(tooLarge.length ? { tooLarge } : {}),
		...(sources.length >= MAX_FILES ? { fileLimitHit: true } : {}),
	};
	await serial(() => writeBrain(map));
	return map;
}

const EXCLUDED_SEGMENT = /(^|\/)(node_modules|\.git|dist|out|build|\.venv|venv|__pycache__|target|vendor|\.my_editor)\//;

/** Updates one file's entry after it is saved (only when a brain already exists and the facts changed). */
export function updateBrainFile(document: vscode.TextDocument): Promise<void> {
	if (languageOf(document.uri.path) === 'other' || document.uri.scheme !== 'file' || !vscode.workspace.getWorkspaceFolder(document.uri)) {
		return Promise.resolve();
	}
	const path = vscode.workspace.asRelativePath(document.uri, false);
	if (EXCLUDED_SEGMENT.test(path) || path.endsWith('.d.ts')) {
		return Promise.resolve();
	}
	const text = document.getText();
	return serial(async () => {
		const map = await readMap();
		if (!map) {
			return;
		}
		const known = new Set([...Object.keys(map.files), path]);
		const before = map.files[path];
		const after = toEntry(path, text, known, before);
		const files = { ...map.files, [path]: after };
		link(files);
		if (JSON.stringify(files) === JSON.stringify(map.files)) {
			return; // Nothing the brain records changed: leave the file alone so git stays quiet.
		}
		const shapeChanged = !before || before.exports.join() !== after.exports.join() || before.role !== after.role;
		await writeBrain({ ...map, files }, shapeChanged);
	});
}

/** Stores the pair's summaries of files and parts (only for files it still has) and refreshes the index. */
export function saveSummaries(summaries: Readonly<Record<string, FileSummary>>, modules: Readonly<Record<string, string>> = {}): Promise<BrainMap | undefined> {
	return serial(async () => {
		const map = await readMap();
		if (!map) {
			return undefined;
		}
		const files = { ...map.files };
		for (const [path, { summary, hash, pieces }] of Object.entries(summaries)) {
			if (files[path]) {
				const { pieces: _old, ...entry } = files[path];
				files[path] = { ...entry, summary, summaryHash: hash, ...(pieces?.length ? { pieces } : {}) };
			}
		}
		const updated = { ...map, files, modules: { ...map.modules, ...modules } };
		await writeBrain(updated);
		return updated;
	});
}

/** Writes a brain note whose generated part sits between the auto markers, keeping whatever the user added. */
export async function writeBrainNote(name: string, title: string, auto: string): Promise<void> {
	const uri = brainUri(name);
	if (uri) {
		const existing = await readText(uri);
		await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(mergeAuto(existing, auto, `# ${title}\n\n`)));
	}
}

/** Fills the index's one-line description while it is still the placeholder. */
export function describeProject(line: string): Promise<void> {
	return serial(async () => {
		const uri = brainUri('index.md');
		const existing = uri && await readText(uri);
		if (uri && existing?.includes(PLACEHOLDER)) {
			await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(existing.replace(PLACEHOLDER, line.replace(/\s+/g, ' ').trim())));
		}
	});
}

async function writeBrain(map: BrainMap, rewriteIndex = true): Promise<void> {
	const mapUri = brainUri('map.json');
	const indexUri = brainUri('index.md');
	if (!mapUri || !indexUri) {
		return;
	}
	await vscode.workspace.fs.writeFile(mapUri, new TextEncoder().encode(JSON.stringify(map, null, '\t') + '\n'));
	if (rewriteIndex) {
		const existing = await readText(indexUri);
		await vscode.workspace.fs.writeFile(indexUri, new TextEncoder().encode(mergeIndex(existing, autoSection(map))));
	}
}

const PLACEHOLDER = 'One line on what this project is and who it is for — edit me.';

function mergeIndex(existing: string | undefined, auto: string): string {
	const name = vscode.workspace.workspaceFolders?.[0]?.name ?? 'Project';
	return mergeAuto(existing, auto, `# ${name}\n\n${PLACEHOLDER}\n\n`, '\n\n## Notes\n\nDecisions, gotchas and anything the pair should always know.\n');
}

/** Replaces only the text between the markers, so the user's own notes survive every rebuild. */
function mergeAuto(existing: string | undefined, auto: string, head: string, tail = '\n'): string {
	const block = `${AUTO_START}\n${auto}\n${AUTO_END}`;
	if (!existing) {
		return `${head}${block}${tail}`;
	}
	const start = existing.indexOf(AUTO_START);
	const end = existing.indexOf(AUTO_END);
	if (start >= 0 && end > start) {
		return existing.slice(0, start) + block + existing.slice(end + AUTO_END.length);
	}
	return `${existing.trimEnd()}\n\n${block}\n`;
}

/** A short, bounded map of the project: stack, modules, and (for small projects) every file's role. */
function autoSection(map: BrainMap): string {
	const entries = Object.entries(map.files);
	const byLanguage = new Map<string, number>();
	const byModule = new Map<string, string[]>();
	for (const [path, entry] of entries) {
		byLanguage.set(entry.language, (byLanguage.get(entry.language) ?? 0) + 1);
		const module = moduleOf(path);
		byModule.set(module, [...(byModule.get(module) ?? []), path]);
	}
	const names: Record<string, string> = { ts: 'TypeScript', js: 'JavaScript', py: 'Python', rs: 'Rust', go: 'Go', c: 'C/C++', other: 'other' };
	const lines = [
		`## Map`,
		'',
		`- **Files:** ${entries.length} (${[...byLanguage].map(([l, n]) => `${names[l]} ${n}`).join(', ')})${map.commit ? ` · built at ${map.commit}` : ''}`,
		`- **Most used:** ${entries.sort((a, b) => b[1].importedBy.length - a[1].importedBy.length).slice(0, 5).filter(([, e]) => e.importedBy.length).map(([p, e]) => `\`${p}\` (${e.importedBy.length})`).join(', ') || 'none yet'}`,
		'',
		'## Modules',
		'',
	];
	const small = entries.length <= 60;
	for (const [module, paths] of [...byModule].sort()) {
		const about = map.modules?.[module];
		lines.push(`- \`${module}\` — ${paths.length} file${paths.length === 1 ? '' : 's'}${about ? `. ${about}` : ''}`);
		if (small) {
			for (const path of paths.sort()) {
				const what = describeEntry(map.files[path]);
				lines.push(`  - \`${path}\`${what ? ` — ${what}` : ''}`);
			}
		}
	}
	const unsummarised = entries.filter(([, e]) => !e.summary && !e.note && !e.role).length;
	const gaps = [
		map.fileLimitHit ? `only the first ${MAX_FILES} code files are mapped` : '',
		map.tooLarge?.length ? `${map.tooLarge.length} file${map.tooLarge.length === 1 ? ' is' : 's are'} too large to read (${map.tooLarge.slice(0, 3).join(', ')}${map.tooLarge.length > 3 ? ', …' : ''})` : '',
		map.modules && unsummarised ? `${unsummarised} file${unsummarised === 1 ? ' has' : 's have'} no summary yet` : '',
	].filter(Boolean);
	if (gaps.length) {
		lines.splice(4, 0, `- **Not covered:** ${gaps.join('; ')}`);
	}
	let text = lines.join('\n');
	if (text.length > INDEX_BUDGET_CHARS) {
		text = `${text.slice(0, INDEX_BUDGET_CHARS)}\n- … (trimmed to keep the brain short; see map.json)`;
	}
	return text;
}

/** What the pair should know about a file's neighbours: files it uses and files that use it. */
export async function neighbourSummary(path: string, limit = 16): Promise<string> {
	const map = await readMap();
	const entry = map?.files[path];
	if (!map || !entry) {
		return '';
	}
	const describe = (p: string) => {
		const what = describeEntry(map.files[p]);
		return `- ${p}${what ? ` — ${what}` : ''}`;
	};
	const uses = entry.imports.slice(0, limit).map(describe);
	const usedBy = entry.importedBy.slice(0, limit).map(describe);
	const module = moduleOf(path);
	const part = map.modules?.[module];
	return [
		part ? `This file is in the part \`${module}\`: ${part}` : '',
		entry.pieces?.length ? `What is where in this file:\n${entry.pieces.map(p => `- lines ${p.start}–${p.end}: ${p.summary}`).join('\n')}` : '',
		uses.length ? `This file uses:\n${uses.join('\n')}` : '',
		usedBy.length ? `Used by:\n${usedBy.join('\n')}` : '',
	].filter(Boolean).join('\n\n');
}
