import { execFile } from 'child_process';
import * as vscode from 'vscode';
import { extractFacts, FileFacts, languageOf, resolveImport } from './facts';

/** One file in `brain/map.json`. `note` is the user's own line and is never overwritten. */
export interface MapEntry extends Omit<FileFacts, 'imports'> {
	readonly imports: string[];
	importedBy: string[];
	readonly note?: string;
}

export interface BrainMap {
	readonly builtAt: string;
	readonly commit: string;
	readonly files: Record<string, MapEntry>;
}

export const SOURCE_GLOB = '**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs,py}';
export const EXCLUDE_GLOB = '{**/node_modules/**,**/.git/**,**/dist/**,**/out/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/.my_editor/**,**/*.d.ts,**/*.min.js}';
const MAX_FILES = 5_000;
const MAX_FILE_BYTES = 400_000;
const AUTO_START = '<!-- my_editor:auto — regenerated by "Build Project Brain"; edit outside these markers -->';
const AUTO_END = '<!-- /my_editor:auto -->';
const INDEX_BUDGET_CHARS = 7_000;

function root(): vscode.Uri | undefined {
	return vscode.workspace.workspaceFolders?.[0]?.uri;
}

function brainUri(name: string): vscode.Uri | undefined {
	const r = root();
	return r && vscode.Uri.joinPath(r, '.my_editor', 'brain', name);
}

export async function readText(uri: vscode.Uri): Promise<string | undefined> {
	try {
		return new TextDecoder().decode(await vscode.workspace.fs.readFile(uri));
	} catch {
		return undefined;
	}
}

function gitHead(cwd: string): Promise<string> {
	return new Promise(resolve => execFile('git', ['rev-parse', '--short', 'HEAD'], { cwd, timeout: 4000 }, (err, out) => resolve(err ? '' : out.trim())));
}

export async function readMap(): Promise<BrainMap | undefined> {
	const uri = brainUri('map.json');
	const text = uri && await readText(uri);
	try {
		return text ? JSON.parse(text) as BrainMap : undefined;
	} catch {
		return undefined;
	}
}

/** Recomputes `importedBy` for every entry from the resolved imports. */
function link(files: Record<string, MapEntry>): void {
	for (const entry of Object.values(files)) {
		entry.importedBy = [];
	}
	for (const [path, entry] of Object.entries(files)) {
		for (const target of entry.imports) {
			files[target]?.importedBy.push(path);
		}
	}
}

function toEntry(path: string, text: string, known: ReadonlySet<string>, previous: MapEntry | undefined): MapEntry {
	const facts = extractFacts(path, text);
	const imports = facts.imports
		.map(spec => resolveImport(path, spec, known))
		.filter((p): p is string => !!p);
	return { ...facts, imports, importedBy: [], ...(previous?.note ? { note: previous.note } : {}) };
}

/** Scans the whole workspace and writes `brain/map.json` and the auto section of `brain/index.md`. */
export async function buildBrain(progress?: vscode.Progress<{ message?: string }>): Promise<BrainMap | undefined> {
	const r = root();
	if (!r) {
		return undefined;
	}
	const sources = (await vscode.workspace.findFiles(SOURCE_GLOB, EXCLUDE_GLOB, MAX_FILES))
		.map(uri => ({ uri, path: vscode.workspace.asRelativePath(uri, false) }))
		.sort((a, b) => a.path.localeCompare(b.path));
	const known = new Set(sources.map(s => s.path));
	const previous = (await readMap())?.files ?? {};
	const files: Record<string, MapEntry> = {};
	for (const [i, { uri, path }] of sources.entries()) {
		if (i % 200 === 0) {
			progress?.report({ message: `${i} of ${sources.length} files` });
		}
		const stat = await vscode.workspace.fs.stat(uri);
		if (stat.size > MAX_FILE_BYTES) {
			continue;
		}
		const text = await readText(uri);
		if (text !== undefined) {
			files[path] = toEntry(path, text, known, previous[path]);
		}
	}
	link(files);
	const map: BrainMap = { builtAt: new Date().toISOString(), commit: await gitHead(r.fsPath), files };
	await writeBrain(map);
	return map;
}

/** Updates one file's entry after it is saved (only when a brain already exists). */
export async function updateBrainFile(document: vscode.TextDocument): Promise<void> {
	if (languageOf(document.uri.path) === 'other' || document.uri.path.includes('/.my_editor/')) {
		return;
	}
	const map = await readMap();
	if (!map) {
		return;
	}
	const path = vscode.workspace.asRelativePath(document.uri, false);
	const known = new Set([...Object.keys(map.files), path]);
	const before = map.files[path];
	const after = toEntry(path, document.getText(), known, before);
	const files = { ...map.files, [path]: after };
	link(files);
	const shapeChanged = !before || before.exports.join() !== after.exports.join() || before.role !== after.role;
	await writeBrain({ ...map, builtAt: new Date().toISOString(), files }, shapeChanged);
}

async function writeBrain(map: BrainMap, rewriteIndex = true): Promise<void> {
	const mapUri = brainUri('map.json');
	const indexUri = brainUri('index.md');
	if (!mapUri || !indexUri) {
		return;
	}
	await vscode.workspace.fs.writeFile(mapUri, new TextEncoder().encode(JSON.stringify(map, null, '\t') + '\n'));
	if (rewriteIndex) {
		const existing = await readText(indexUri);
		await vscode.workspace.fs.writeFile(indexUri, new TextEncoder().encode(mergeIndex(existing, autoSection(map))));
	}
}

/** Replaces only the text between the markers, so the user's own notes survive every rebuild. */
function mergeIndex(existing: string | undefined, auto: string): string {
	const block = `${AUTO_START}\n${auto}\n${AUTO_END}`;
	if (!existing) {
		const name = vscode.workspace.workspaceFolders?.[0]?.name ?? 'Project';
		return `# ${name}\n\nOne line on what this project is and who it is for — edit me.\n\n${block}\n\n## Notes\n\nDecisions, gotchas and anything the pair should always know.\n`;
	}
	const start = existing.indexOf(AUTO_START);
	const end = existing.indexOf(AUTO_END);
	if (start >= 0 && end > start) {
		return existing.slice(0, start) + block + existing.slice(end + AUTO_END.length);
	}
	return `${existing.trimEnd()}\n\n${block}\n`;
}

/** A short, bounded map of the project: stack, modules, and (for small projects) every file's role. */
function autoSection(map: BrainMap): string {
	const entries = Object.entries(map.files);
	const byLanguage = new Map<string, number>();
	const byModule = new Map<string, string[]>();
	for (const [path, entry] of entries) {
		byLanguage.set(entry.language, (byLanguage.get(entry.language) ?? 0) + 1);
		const module = path.includes('/') ? path.split('/').slice(0, path.split('/').length > 2 ? 2 : 1).join('/') : '.';
		byModule.set(module, [...(byModule.get(module) ?? []), path]);
	}
	const names: Record<string, string> = { ts: 'TypeScript', js: 'JavaScript', py: 'Python', other: 'other' };
	const lines = [
		`## Map`,
		'',
		`- **Files:** ${entries.length} (${[...byLanguage].map(([l, n]) => `${names[l]} ${n}`).join(', ')})${map.commit ? ` · built at ${map.commit}` : ''}`,
		`- **Most used:** ${entries.sort((a, b) => b[1].importedBy.length - a[1].importedBy.length).slice(0, 5).filter(([, e]) => e.importedBy.length).map(([p, e]) => `\`${p}\` (${e.importedBy.length})`).join(', ') || 'none yet'}`,
		'',
		'## Modules',
		'',
	];
	const small = entries.length <= 60;
	for (const [module, paths] of [...byModule].sort()) {
		lines.push(`- \`${module}\` — ${paths.length} file${paths.length === 1 ? '' : 's'}`);
		if (small) {
			for (const path of paths.sort()) {
				const entry = map.files[path];
				const what = entry.note ?? entry.role ?? (entry.exports.length ? `exports ${entry.exports.slice(0, 4).join(', ')}` : '');
				lines.push(`  - \`${path}\`${what ? ` — ${what}` : ''}`);
			}
		}
	}
	let text = lines.join('\n');
	if (text.length > INDEX_BUDGET_CHARS) {
		text = `${text.slice(0, INDEX_BUDGET_CHARS)}\n- … (trimmed to keep the brain short; see map.json)`;
	}
	return text;
}

/** What the pair should know about a file's neighbours: files it uses and files that use it. */
export async function neighbourSummary(path: string, limit = 16): Promise<string> {
	const map = await readMap();
	const entry = map?.files[path];
	if (!map || !entry) {
		return '';
	}
	const describe = (p: string) => {
		const e = map.files[p];
		const what = e?.note ?? e?.role ?? (e?.exports.length ? `exports ${e.exports.slice(0, 6).join(', ')}` : '');
		return `- ${p}${what ? ` — ${what}` : ''}`;
	};
	const uses = entry.imports.slice(0, limit).map(describe);
	const usedBy = entry.importedBy.slice(0, limit).map(describe);
	return [
		uses.length ? `This file uses:\n${uses.join('\n')}` : '',
		usedBy.length ? `Used by:\n${usedBy.join('\n')}` : '',
	].filter(Boolean).join('\n\n');
}
